In [25]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/haberman.csv')

In [26]:
df.head(5)

   30  64   1  1.1
0  30  62   3    1
1  30  65   0    1
2  31  59   2    1
3  31  65   4    1
4  33  58  10    1

In [27]:
df['age'] = df.iloc[:,0]
df['year'] = df.iloc[:,1]
df['survived'] = df.iloc[:,3]

In [28]:
df = df.drop('30',axis=1)
df = df.drop('64',axis=1)
df = df.drop('1',axis=1)
df = df.drop('1.1',axis=1)

In [29]:
df.head(10)

   age  year  survived
0   30    62         1
1   30    65         1
2   31    59         1
3   31    65         1
4   33    58         1
5   33    60         1
6   34    59         2
7   34    66         2
8   34    58         1
9   34    60         1

In [30]:
x = df.drop('survived',axis=1)
y = df['survived']

In [31]:
from sklearn.model_selection import cross_val_score

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
lr = LogisticRegression()
svm = SVC(probability=True)
dt = DecisionTreeClassifier()
print(np.mean(cross_val_score(lr,x,y,cv=10,scoring='accuracy')))
print(np.mean(cross_val_score(dt,x,y,cv=10,scoring='accuracy')))
print(np.mean(cross_val_score(svm,x,y,cv=10,scoring='accuracy')))

0.7344086021505376
0.5296774193548387
0.7344086021505376

In [39]:
from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators = [('lr',lr),('svm',svm),('dt',dt)],voting='hard')
print(np.mean(cross_val_score(vc,x,y,cv=10,scoring='accuracy')))

0.7344086021505376

In [41]:
for i in range(1,4):
  for j in range(1,4):
    for k in range(1,4):
      vc = VotingClassifier(estimators = [('lr',lr),('svm',svm),('dt',dt)],voting='hard',weights=[i,j,k])
      print("for i = ",i,"for j =",j,"for k =",k,np.mean(cross_val_score(vc,x,y,cv=10,scoring='accuracy')))

for i =  1 for j = 1 for k = 1 0.7344086021505376
for i =  1 for j = 1 for k = 2 0.7344086021505376
for i =  1 for j = 1 for k = 3 0.5329032258064517
for i =  1 for j = 2 for k = 1 0.7344086021505376
for i =  1 for j = 2 for k = 2 0.7344086021505376
for i =  1 for j = 2 for k = 3 0.7344086021505376
for i =  1 for j = 3 for k = 1 0.7344086021505376
for i =  1 for j = 3 for k = 2 0.7344086021505376
for i =  1 for j = 3 for k = 3 0.7344086021505376
for i =  2 for j = 1 for k = 1 0.7344086021505376
for i =  2 for j = 1 for k = 2 0.7344086021505376
for i =  2 for j = 1 for k = 3 0.7344086021505376
for i =  2 for j = 2 for k = 1 0.7344086021505376
for i =  2 for j = 2 for k = 2 0.7344086021505376
for i =  2 for j = 2 for k = 3 0.7344086021505376
for i =  2 for j = 3 for k = 1 0.7344086021505376
for i =  2 for j = 3 for k = 2 0.7344086021505376
for i =  2 for j = 3 for k = 3 0.7344086021505376
for i =  3 for j = 1 for k = 1 0.7344086021505376
for i =  3 for j = 1 for k = 2 0.7344086021505376
for i =  3 for j = 1 for k = 3 0.7344086021505376
for i =  3 for j = 2 for k = 1 0.7344086021505376
for i =  3 for j = 2 for k = 2 0.7344086021505376
for i =  3 for j = 2 for k = 3 0.7344086021505376
for i =  3 for j = 3 for k = 1 0.7344086021505376
for i =  3 for j = 3 for k = 2 0.7344086021505376
for i =  3 for j = 3 for k = 3 0.7344086021505376